### ISSUE TITLE
recovery not updating to latest while OTA.

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_Updater#82]
device: vayu
build: 14-09-2024

I enabled the update recovery toggle in updater settings and updated from 8th sep build to 14th sep build via ota. but it seems recovery image not get updated in the process. it still remain on 8th sep.

Expected behaviour:
recovery image should update along with system if enabled.
 
![Screenshot_20240914-160227_Updater](https://github.com/user-attachments/assets/1658fb6c-71cc-4118-a8dd-52ae399ae96f)

**Comment by gwolf2u** [comment]
please use issue_tracker
